services:
  app:
    build: .
    container_name: mundial_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://mundial-2026-db.postgres.database.azure.com:5432/mundial_2026
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Mundial2026#Bosque
      JWT_SECRET: QJoKMMkOnk6M9+f37cAbW4AmU/9DwQUE6pKAQXCkzGA=
      API_FOOTBALL_URL: https://v3.football.api-sports.io
      API_FOOTBALL_KEY: 6ba0efffd79d5e7f49ec8b02c14cccb3

  frontend:
    build:
      context: ../../frontend-web/frontend_mundial
      args:
        VITE_API_BASE_URL: http://localhost:8080
    container_name: mundial_frontend
    ports:
      - "80:80"
    depends_on:
      - app