spring.application.name=mundial_2026

spring.datasource.url=jdbc:postgresql://localhost:5432/mundial_2026
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=QJoKMMkOnk6M9+f37cAbW4AmU/9DwQUE6pKAQXCkzGA=

api.football.url=https://v3.football.api-sports.io
api.football.key=6ba0efffd79d5e7f49ec8b02c14cccb3