sonar.projectKey=jsbecerrap_prueba_sonarCloud_frontend
sonar.organization=jsbecerrap
sonar.projectName=mundial-2026-frontend
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.test.ts,**/*.spec.ts,**/mockDb.ts,**/poolsMockDb.ts
sonar.sourceEncoding=UTF-8